name: agrimitra
description: AgriMitra MVP
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  crypto: ^3.0.3
  http: ^1.2.1              # API calls
  geolocator: ^11.0.0       # location services
  image_picker: ^1.0.7      # pick/take leaf photos (disease.dart)
  google_generative_ai: ^0.4.4  # Gemini client (disease.dart)
  shared_preferences: ^2.2.2     # store API key locally
  url_launcher: ^6.3.0           # <-- added for GovtPage links

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/agrimitra.png
